name: Trigger auto deployment for calculationgame

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/calculationgame-AutoDeployTrigger-d5a6c6eb-053a-41ff-99b1-d202bb193603.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CALCULATIONGAME_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CALCULATIONGAME_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CALCULATIONGAME_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: calulationgame.azurecr.io
          registryUsername: ${{ secrets.CALCULATIONGAME_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CALCULATIONGAME_REGISTRY_PASSWORD }}
          containerAppName: calculationgame
          resourceGroup: shiv-dev-learning
          imageToBuild: calulationgame.azurecr.io/calculationgame:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


